<a href="https://colab.research.google.com/github/AlexandreMachineLearning/Regressao-arvores/blob/main/Q_7_Regressao_arvores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Usando uma árvore de regressão sem podas, com quebras baseadas no MSE e 10-fold crossvalidation, dê os MAE médios para treino e validação para os dados em regressao_q7.csv.

Passo 1 - Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Passo 2 - Criação e Carregamento do dataframe

In [2]:
regression_tree_df=pd.read_csv('/content/regressao_Q7.csv')

In [3]:
regression_tree_df

x0        x1        x2  ...       x18       x19      target
0     0.591690  0.591690  1.172172  ...  0.636366  1.070023  183.381979
1     0.617718  0.617718  1.066885  ...  0.605663  0.800897  171.166244
2    -0.091250 -0.091250  0.460780  ... -0.826144 -0.361113 -310.459284
3    -0.264834 -0.264834  1.061765  ...  0.916976  1.198790  228.015980
4     0.308724  0.308724  0.793572  ... -0.607837  0.038154  -51.379428
...        ...       ...       ...  ...       ...       ...         ...
1995  0.653463  0.653463  1.043070  ...  0.611042 -0.233265   70.740241
1996  2.141161  2.141161  2.645677  ...  0.930585  1.990016  799.716237
1997  0.570490  0.570490  1.162729  ...  1.184509  1.334873  342.857246
1998  1.043742  1.043742  1.430562  ...  1.280729  1.513731  466.400273
1999 -0.897494 -0.897494 -0.157972  ...  0.121557 -0.304295 -376.497416

[2000 rows x 21 columns]

In [4]:
regression_tree_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x0      2000 non-null   float64
 1   x1      2000 non-null   float64
 2   x2      2000 non-null   float64
 3   x3      2000 non-null   float64
 4   x4      2000 non-null   float64
 5   x5      2000 non-null   float64
 6   x6      2000 non-null   float64
 7   x7      2000 non-null   float64
 8   x8      2000 non-null   float64
 9   x9      2000 non-null   float64
 10  x10     2000 non-null   float64
 11  x11     2000 non-null   float64
 12  x12     2000 non-null   float64
 13  x13     2000 non-null   float64
 14  x14     2000 non-null   float64
 15  x15     2000 non-null   float64
 16  x16     2000 non-null   float64
 17  x17     2000 non-null   float64
 18  x18     2000 non-null   float64
 19  x19     2000 non-null   float64
 20  target  2000 non-null   float64
dtypes: float64(21)
memory usage: 328.2 KB

In [5]:
regression_tree_df.isnull().sum()

x0        0
x1        0
x2        0
x3        0
x4        0
x5        0
x6        0
x7        0
x8        0
x9        0
x10       0
x11       0
x12       0
x13       0
x14       0
x15       0
x16       0
x17       0
x18       0
x19       0
target    0
dtype: int64

Passo 3 - Separação dos dados

In [6]:
X_regression_tree=regression_tree_df.iloc[:,0:20].values

In [7]:
X_regression_tree

array([[ 0.59169004,  0.59169004,  1.17217183, ...,  0.22801365,
         0.63636576,  1.07002268],
       [ 0.61771849,  0.61771849,  1.06688505, ...,  0.32706374,
         0.60566298,  0.80089738],
       [-0.09125019, -0.09125019,  0.46077982, ..., -1.00180499,
        -0.82614424, -0.36111299],
       ...,
       [ 0.57048987,  0.57048987,  1.16272867, ...,  0.87200544,
         1.18450874,  1.33487346],
       [ 1.04374214,  1.04374214,  1.43056249, ...,  1.13683769,
         1.28072937,  1.51373134],
       [-0.89749385, -0.89749385, -0.15797229, ..., -0.79155455,
         0.12155698, -0.3042951 ]])

In [8]:
y_regression_tree=regression_tree_df.iloc[:,20].values

In [9]:
y_regression_tree

array([ 183.38197899,  171.16624379, -310.45928386, ...,  342.85724559,
        466.40027284, -376.49741594])

Passo 4 - Separação dos dados de treinamento e teste

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
X_regression_treinamento, X_regression_teste, y_regression_treinamento, y_regression_teste = train_test_split(X_regression_tree, y_regression_tree, test_size = 0.30)

In [13]:
X_regression_treinamento.shape, y_regression_treinamento.shape

((1400, 20), (1400,))

Passo 5 - Previsões

In [14]:
from sklearn.tree import DecisionTreeRegressor


In [15]:
regressor_arvore = DecisionTreeRegressor()
regressor_arvore.fit(X_regression_treinamento, y_regression_treinamento)

DecisionTreeRegressor()

In [16]:
previsoes=regressor_arvore.predict(X_regression_teste)

In [17]:
previsoes

array([   11.01775103,  -183.36235254,   -45.71262773,   524.04957407,
         -33.20183784,   234.72570961,   889.19446299,   102.03195849,
         510.05859121,  -118.57994012,  -246.98198017,   136.70837291,
        -280.69701525,   561.15270585,  1058.98752941,  -178.77640638,
        -608.69700537,   122.59197597,   246.62798641,   -76.68539841,
         228.3640075 ,   554.85178541,    67.36769767,   379.94756993,
         798.98080083,   813.29766265,   621.9693399 ,  -311.61201202,
         690.97550765,   518.55199368,   144.48316922,  -354.29759813,
          -3.40574208,  -853.86897966,   884.43375692,   -78.0313468 ,
        -916.46287651,  1022.78897795,  -165.57682814,   221.19202352,
         889.19446299,   468.81924141,   141.55912224,   722.85481367,
        -689.79697679,    41.92158744,  -822.01537929,   880.2685154 ,
         317.82663477,   530.09974393,   371.89891527,   239.67570402,
         -10.56952963,  -153.85638562,  -342.79687697,   238.94508419,
      

In [18]:
 y_regression_teste

array([ 6.20135265e+01, -2.16544203e+02,  5.08214157e+01,  5.39572515e+02,
       -2.49253887e+01,  2.58428866e+02,  9.19413936e+02,  1.00487153e+02,
        4.21417985e+02, -1.15275544e+02, -1.57835711e+02,  5.13708198e+01,
       -2.25099269e+02,  5.62231527e+02,  1.07106603e+03, -1.32122851e+02,
       -6.19732113e+02,  1.41210128e+02,  2.09234024e+02, -8.37442160e+01,
        2.65696898e+02,  5.79132337e+02, -3.14118359e+01,  3.83131819e+02,
        8.63381599e+02,  7.46214366e+02,  6.75060254e+02, -3.44907861e+02,
        7.27281657e+02,  5.34651277e+02,  3.56776563e+02, -2.58915548e+02,
       -5.07328410e+01, -9.08012271e+02,  9.56599222e+02, -7.08844559e+01,
       -9.83825206e+02,  9.01646049e+02, -1.91404153e+02,  1.71317542e+02,
        8.92821536e+02,  5.38879774e+02, -6.58227744e-01,  4.29579982e+02,
       -7.04008884e+02,  3.99290192e+01, -7.44349979e+02,  7.89897891e+02,
        3.53415913e+02,  5.82927948e+02,  2.91094250e+02,  2.71558669e+02,
        4.16176191e+01, -

Passo 6 - Cálculo do MAE

In [19]:
from sklearn.metrics import accuracy_score, classification_report

In [20]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_regression_teste, previsoes)

54.574060237187815